[general]
live_config_reload = true

[bell]
duration = 0

[colors.bright]
black = "#6c6f85"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#bcc0cc"

[colors.normal]
black = "#5c5f77"
red = "#d20f39"
green = "#40a02b"
yellow = "#df8e1d"
blue = "#1e66f5"
magenta = "#ea76cb"
cyan = "#179299"
white = "#acb0be"

[colors.primary]
background = "#eff1f5"
foreground = "#4c4f69"

[colors.selection]
background = "#dc8a78"
foreground = "#eff1f5"

[colors.cursor]
cursor = "#dc8a78"
text = "#eff1f5"

[cursor]
unfocused_hollow = true

[cursor.style]
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
size = 11.0

[font.bold]
family = "MesloLGS Nerd Font Mono"
style = "Bold"

[font.italic]
family = "MesloLGS Nerd Font Mono"
style = "Italic"

[font.normal]
family = "MesloLGS Nerd Font Mono"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[window]
decorations = "none"
dynamic_padding = true
startup_mode = "Maximized"

[window.padding]
x = 25
y = 20
